FROM osrf/ros:galactic-desktop

# Define build arguments for flexibility
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG ROBOT_TYPE=locobot4
ARG ROBOT_IP=10.253.20.224

# Install necessary packages
RUN apt-get update \ 
    && apt-get install -y \ 
    nano \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    debconf-utils \
    locales \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Preconfigure keyboard settings
RUN echo "keyboard-configuration keyboard-configuration/layoutcode select us" | debconf-set-selections && \
    echo "keyboard-configuration keyboard-configuration/xkb-keymap select us" | debconf-set-selections && \
    echo "keyboard-configuration keyboard-configuration/model select Generic 105-key PC (intl)" | debconf-set-selections && \
    echo "keyboard-configuration keyboard-configuration/layout select English (US)" | debconf-set-selections && \
    echo "keyboard-configuration keyboard-configuration/variant select English (US)" | debconf-set-selections

# Set the locale
RUN locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8

# Create a non-root user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && mkdir /home/$USERNAME/.config && chown $USER_UID:$USER_GID /home/$USERNAME/.config

# Setup sudo for the new user
RUN echo $USERNAME ALL=\(\root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

# Set the home directory and working directory for the new user
ENV HOME=/home/$USERNAME
WORKDIR $HOME

# Create the interbotix_ws directory in the home directory
RUN mkdir -p $HOME/interbotix_ws && chown $USERNAME:$USERNAME $HOME/interbotix_ws

# Set .bashrc file ownership and append ROS setup
RUN touch $HOME/.bashrc && chown $USERNAME:$USERNAME $HOME/.bashrc && \
    echo "source /opt/ros/galactic/setup.bash" >> $HOME/.bashrc && \
    echo "source $HOME/.bashrc" >> $HOME/.bashrc

# Copy and configure the install script
COPY /xslocobot_remote_install.sh $HOME/xslocobot_remote_install.sh
RUN chmod +x $HOME/xslocobot_remote_install.sh && \
    chown $USERNAME:$USERNAME $HOME/xslocobot_remote_install.sh

# Switch to the non-root user and execute the installation script with build arguments
USER $USERNAME
RUN $HOME/xslocobot_remote_install.sh -d galactic -b create3 -r $ROBOT_TYPE -i $ROBOT_IP -n -p $HOME/interbotix_ws

# Ensure that user-relative paths work
CMD ["/bin/bash"]
